<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Zf2menu\Module'                          => __DIR__ . '/Module.php',
    'Zf2menu\Controller\MenusController'      => __DIR__ . '/src/Zf2menu/Controller/MenusController.php',
    'Zf2menu\Controller\Zf2menuAppController' => __DIR__ . '/src/Zf2menu/Controller/Zf2menuAppController.php',
    'Zf2menu\Entity\Menus'                    => __DIR__ . '/src/Zf2menu/Entity/Menus.php',
    'Zf2menu\Form\MenusForm'                  => __DIR__ . '/src/Zf2menu/Form/MenusForm.php',
    'Zf2menu\Form\MenusSearchForm'            => __DIR__ . '/src/Zf2menu/Form/MenusSearchForm.php',
    'Zf2menu\Table\MenusTable'                => __DIR__ . '/src/Zf2menu/Table/MenusTable.php',
    'Zf2menu\View\Helper\Navigationhelper'    => __DIR__ . '/src/Zf2menu/View/Helper/Navigationhelper.php',
);
