<?php
$title     = 'Menus';
$this->headTitle($title);
$url_order = 'ASC';
if ($order_by == 'name') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'type') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'resource_id') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'url') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'target') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'parent_id') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'status') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'created') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'modified') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
}


$urlarray['name']        = array ('order_by' => 'name', 'order' => $url_order);
$urlarray['type']        = array ('order_by' => 'type', 'order' => $url_order);
$urlarray['resource_id'] = array ('order_by' => 'resource_id', 'order' => $url_order);
$urlarray['url']         = array ('order_by' => 'url', 'order' => $url_order);
$urlarray['target']      = array ('order_by' => 'target', 'order' => $url_order);
$urlarray['parent_id']   = array ('order_by' => 'parent_id', 'order' => $url_order);
$urlarray['status']      = array ('order_by' => 'status', 'order' => $url_order);
$urlarray['created']     = array ('order_by' => 'created', 'order' => $url_order);
$urlarray['modified']    = array ('order_by' => 'modified', 'order' => $url_order);


$displayRange_array = array (
    'page'     => $page,
    'order_by' => $order_by,
    'order'    => $order,
);

if (!empty($search_by)) {
    foreach ($urlarray as $key => $val) {
        $urlarray[$key]['search_by'] = $search_by;
    }
    $displayRange_array['search_by'] = $search_by;
}
foreach ($urlarray as $key => $val) {
    $urlarray[$key]['item_per_page'] = $item_per_page;
    $urlarray[$key]['page']          = $page;
}
?>
<div class="occ-container">
    <div class="row">
        <?php echo $this->partial('partial/message.phtml', array ('flashMessages' => $this->flashMessages, 'error' => $this->error)); ?>
        <!-- FILTER -->
        <div class="col-md-24">
            <div class="panel">
                <div class="panel-heading">
                    Filter Menus                    
                </div>

                <div class="panel-body" style="display: none;">
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url('menus/search'));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    ?>
                    <input type="hidden"
                           name="item_per_page" value="<?php echo $item_per_page; ?>">
                           <?php
                           foreach ($form as $element) :
                               ?>
                        <div
                            class="form-group <?php if ($this->formElementErrors($element)) echo "error" ?>">
                            <label class="col-lg-4 control-label"><?php echo $element->getLabel() ?></label>
                            <div class="col-lg-8 controls">
                                <?php
                                echo $this->formElement($element);
                                if ($this->formElementErrors($element)) :
                                    ?>
                                    <span
                                        class="help-inline"><?php echo $this->formElementErrors($element); ?></span>

                                    <?php
                                endif;
                                ?>
                            </div>
                        </div>
                        <?php
                    endforeach
                    ;
                    echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>


        <!-- LIST -->
        <div class="col-md-24">
            <div class="panel">
                <div class="panel-heading">
                    <?php echo $this->escapeHtml($title); ?>
                    <span class="dropdown pull-right tools">
                        <?php                        
                        if ($this->UtilHelper()->displayLink('menus/add')) {
                            ?>
                            <a href="<?php echo $this->url('menus/add'); ?>" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Add New </a>
                            <?php
                        }
                        if ($this->UtilHelper()->displayLink('menus/reorder')) {
                            ?>
                            <a href="<?php echo $this->url('menus/reorder'); ?>" class="btn btn-primary">Reorder menus</a>
                            <?php
                        }
                        ?>
                        <?php echo $this->partial('partial/page_range.phtml'); ?>
                    </span>
                </div>
                <div class="panel-body">
                    <div id="searchresults">
                        <table class="table table-hover general-table">
                            <colgroup></colgroup>
                            <colgroup></colgroup>
                            <colgroup></colgroup>
                            <colgroup style="width: 80px;"></colgroup>
                            <thead>
                                <tr>
                                    <th><a href="<?php echo $this->url($pageAction, $urlarray['name']); ?>">Name <?php if ($order_by == 'name'): ?><?php echo $url_order == 'ASC' ? '&#8595;' : '&#8593;' ?><?php endif; ?></a></th>
                                    <th><a href="<?php echo $this->url($pageAction, $urlarray['parent_id']); ?>">Parent <?php if ($order_by == 'parent_id'): ?><?php echo $url_order == 'ASC' ? '&#8595;' : '&#8593;' ?><?php endif; ?></a></th>
                                    <th><a href="<?php echo $this->url($pageAction, $urlarray['status']); ?>">Status <?php if ($order_by == 'status'): ?><?php echo $url_order == 'ASC' ? '&#8595;' : '&#8593;' ?><?php endif; ?></a></th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($paginator as $row) : ?>
                                    <tr>
                                        <td><a href="<?php echo empty($row->type) ? $this->url($row->resource_name) : $row->url; ?>" target="_blank"> <?php echo $this->translate($this->escapeHtml($row->name)); ?></a></td>
                                        <td><?php echo $this->escapeHtml($row->parent_name); ?></td>
                                        <td><?php if ($row->status == 1) { ?> <i class="glyphicon glyphicon-ok"></i> <?php } ?></td>

                                        <td>
                                            <a href="<?php echo $this->url('menus/edit', array ('id' => $row->id)); ?>" class="btn btn-default btn-xs"><i class="glyphicon glyphicon-pencil"></i></a>
                                            <?php
                                            $delurl = $this->url('menus/delete', array (
                                                'id' => $row->id,
                                            ));
                                            ?>
                                            <div style="display: none;">
                                                <form action="<?php echo $delurl; ?>" method="post" id="post_<?php echo $row->id; ?>" name="post_<?php echo $row->id; ?>">
                                                    <input type="hidden" name="id" value="<?php echo (int) $row->id; ?>" />
                                                </form>
                                            </div>
                                            <a onclick="if (confirm('Are you sure you want to delete <?php echo $row->id; ?>?')) {
                                                        document.<?php echo "post_" . $row->id; ?>.submit();
                                                    }
                                                    event.returnValue = false;
                                                    return false;" href="#" class="btn btn-default btn-xs"><i class="glyphicon glyphicon-remove"></i></a>

                                        </td>

                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-md-12">
                                <?php echo $this->partial('partial/table_total_count.phtml', array ('totalRecord' => $totalRecord, 'currentPage' => $currentPage, 'totalPage' => $totalPage)); ?>
                            </div>
                            <div class="col-md-12">
                                <?php
                                echo $this->paginationControl(
                                        $paginator, 'Sliding', 'paginator-slide', array ('order_by' => $order_by, 'order' => $order, 'search_by' => $search_by, 'pageAction' => $pageAction, 'item_per_page' => $item_per_page)
                                );
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
