<?php
$title = 'Menus';
$this->headTitle($title);
?>
<?php echo $this->partial('partial/menujs.phtml'); ?>
<div class="occ-container">
    <div class="row">
        <?php echo $this->partial('partial/message.phtml', array('flashMessages' => $this->flashMessages, 'error' => $this->error)); ?>

        <div class="col-md-24">
            <div class="panel">
                <div class="panel-heading">
                    <?php echo $this->escapeHtml($title); ?>
                    <span class="dropdown pull-right tools">
                        <?php
                        if ($this->UtilHelper()->displayLink('menus/index')) {
                            ?>
                            <a class="btn btn-primary" href="<?php echo $this->url('menus/index'); ?>">List menus</a>
                            <?php
                        }
                        ?>
                        <?php
                        if ($this->UtilHelper()->displayLink('menus/add')) {
                            ?>
                            <a class="btn btn-primary" href="<?php echo $this->url('menus/add'); ?>"><i class="fa fa-plus-circle"></i> Add New </a>
                            <?php
                        }
                        ?>
                    </span>
                </div>
                <div class="panel-body">
                    <div id="searchresults">
                        <table class="table table-hover general-table">
                            <colgroup></colgroup>
                            <colgroup style="width: 80px;"></colgroup>
                            <?php
                            if (!empty($data)) {
                                foreach ($data as $row) {
                                    echo $this->partial('partial/navigation_li.phtml', array ('data' => $row, 'type' => 'reorder', 'lavel' => 0));
                                }
                            }
                            ?>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
